library(MASS)
library(pwr)
library(compiler)
library(truncnorm)
library(truncdist)
library(reshape2)
library(dplyr)
library(data.table)
library(foreach)
library(doMC)
library(meta)
library(metafor)
library(progress)

source("helpers/helpers.R")
source("sim-studies/sim-studies.R")
source("MA-methods/1-RMA.R")
source("MA-methods/2-p-curve.R")
source("MA-methods/3-PET-PEESE.R")

#source("start.R")
#install.packages(c("MASS", "pwr", "compiler", "truncnorm", "truncdist", "dplyr", "data.table", "foreach", "doMC", "meta", "progress")) 